export const watchlist = [
    "methylparaben",
    "propylparaben",
    "butylparaben",
    "ethylparaben",
    "isobutylparaben",
    "isopropylparaben",
    "phthalate",
    "dibutyl phthalate",
    "diethyl phthalate",
    "dimethyl phthalate",
    "formaldehyde",
    "dmdm hydantoin",
    "quaternium-15",
    "imidazolidinyl urea",
    "diazolidinyl urea",
    "2-bromo-2-nitropropane-1,3-diol",
    "bronopol",
    "sodium lauryl sulfate",
    "sls",
    "sodium laureth sulfate",
    "sles",
    "ammonium lauryl sulfate",
    "triclosan",
    "triclocarban",
    "toluene",
    "benzene",
    "xylene",
    "ethylbenzene",
    "cumene",
    "fd&c",
    "d&c",
    "yellow 5",
    "red 40",
    "blue 1",
    "lead",
    "mercury",
    "cadmium",
    "chromium",
    "arsenic",
    "octinoxate",
    "oxybenzone",
    "butylated hydroxytoluene",
    "butylphenyl methylpropional",
    "Lilial"
];